########################################################################
#
# This CMakeLists.txt file exists mostly to list the subdirectories
# for libraries built by this project.
#
########################################################################
add_subdirectory({{cookiecutter.mainlib}})
