########################################################################
# Copyright {{ current_year }} by the copyright holders
# named in COPYING.md.
#
# Licensed under: {{ cookiecutter.license }}
# See https://spdx.dev or LICENSE.md in this
# project for the license text.
########################################################################

########################################################################
#
# This CMakeLists.txt file exists mostly to list the subdirectories
# for libraries built by this project.
#
########################################################################
add_subdirectory({{cookiecutter.mainlib}})
