#!/usr/bin/env python

import sys
import argparse

class Context:
      def __init__(self):
            self.parser = argparse.ArgumentParser()
            self.parser.add_argument("-G", "--generator",
                                     action="store",
                                     help='Set the CMake generator type')
            self.parser.add_argument("-D",
                                     action="append",
                                     dest='definitions',
                                     help='Define a CMake value.')
            self.parser.add_argument("--short-build-dir",
                                     action='store_true',
                                     default=False,
                                     help='Do not append the multiarch triple '
                                          'to the build directory.')
            self.parser.add_argument("--build-type",
                                     action="store",
                                     choices=['Debug',
                                              'Release',
                                              'RelWithDebInfo',
                                              'MinSizeRel'],
                                     default="Debug",
                                     help='CMake build type.')
            self.parser.add_argument("--no-compile-commands-export",
                                     action='store_true',
                                     default=False,
                                     help='Don\'t export compile_commands.json file.')
            self.parser.add_argument("--roll-build-dir",
                                     action='store_true',
                                     default=False,
                                     help='Roll the build directory.')
            self.parser.add_argument("--cpp-compiler",
                                     action='store',
                                     default='c++',
                                     help='Set the C++ compiler value CXX.')
            self.parser.add_argument("--c-compiler",
                                     action='store',
                                     default='cc',
                                     help='Set the C compiler value CC')

      
      def parse(self, args = sys.argv[1:]):
            parsed_args = self.parser.parse_args(args)
            self.generator = parsed_args.generator
            self.short_build_dir = parsed_args.short_build_dir
            self.build_type = parsed_args.build_type,
            self.no_compile_commands_export = parsed_args.no_compile_commands_export
            self.roll_build_dir = parsed_args.roll_build_dir
            self.cpp_compiler = parsed_args.cpp_compiler
            self.c_compiler = parsed_args.c_compiler
                                     

      def dump_args(self):
            print('self.generator: ', self.generator)
            print('self.short_build_dir: ', self.short_build_dir)
            print('self.build_type: ', self.build_type)
            print('self.no_compile_commands_export: ', self.no_compile_commands_export)
            print('self.roll_build_dir: ', self.roll_build_dir)
            print('self.cpp_compiler: ', self.cpp_compiler)
            print('self.c_compiler: ', self.c_compiler)

def main():
      context = Context()
      context.parse()
      context.dump_args()


if __name__ == '__main__':
      main()
